[project]
name = "jed"
version = "0.2.0"
description = "jed: sed for JSON"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lark>=1.3.1",
    "pygments>=2.19.2",
    "pytest>=9.0.2",
]
